###########################
#####                 #####
####                   ####
###   Author: HALD91    ###
###   Version: 1.4.7.0  ###
####                   ####
#####                 #####
###########################

## To make colored text use minecraft color codes: https://www.colorschemer.com/minecraft-color-codes/
## Add your rules like the example down below: (Do not change the Rules tag)

Rules:
  - '&dRule1'
  - '&dRule2'

ServerInfo:
  - '&eThis server is an awesome server'
  - '&eRemember to have fun!'

# Set ThePrefix here
Prefix: '&7&6YourPrefix&7&r'